#!/bin/sh

# REQUIRE: DAEMON
# PROVIDE: keyfetcher
# KEYWORD: shutdown

export PATH=/usr/local/bin:$PATH

. /etc/rc.subr

name="keyfetcher"
load_rc_config $name

rcvar="${name}_enable"
pidfile="/var/run/$name.pid"
command="/usr/sbin/daemon"
command_args="-c -r -t $name -S -T $name -P $pidfile /usr/local/keyserver/bin/keyfetcher"

run_rc_command "$1"
