#!/bin/sh

# REQUIRE: DAEMON
# PROVIDE: keyserver
# KEYWORD: shutdown

export PATH=/usr/local/bin:$PATH

. /etc/rc.subr

name="keyserver"
rcvar="${name}_enable"

pidfile="/var/run/${name}.pid"
command="/usr/sbin/daemon"
command_args="-c -r -t ${name} -S -T ${name} -P ${pidfile} /opt/keyserver/bin/keyserver"

load_rc_config ${name}
: ${keyserver_enable:=no}

run_rc_command "$1"
